<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <StartupObject>WoodMindCAM.Program</StartupObject>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="set PLUGIN_DIR=%25AppData%25\SketchUp\SketchUp 2024\SketchUp\Plugins\WoodMindCAM\bin&#xD;&#xA;&#xD;&#xA;if not exist &quot;%25PLUGIN_DIR%25&quot; mkdir &quot;%25PLUGIN_DIR%25&quot;&#xD;&#xA;&#xD;&#xA;xcopy &quot;$(TargetDir)*&quot; &quot;%25PLUGIN_DIR%25\&quot; /E /Y /I /Q" />
  </Target>

</Project>